# Generated by Django 5.1.12 on 2025-10-08 20:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0002_initial'),
        ('artifacts', '0002_initial'),
        ('goals', '0001_initial'),
        ('plans', '0001_initial'),
        ('worlds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ref', models.CharField(max_length=128)),
                ('mode', models.CharField(max_length=8)),
                ('adapter', models.CharField(max_length=8)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('preempted', 'Preempted')], default='pending', max_length=16)),
                ('error_code', models.CharField(blank=True, max_length=64, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('image_digest_expected', models.CharField(blank=True, max_length=71, null=True)),
                ('image_digest_actual', models.CharField(blank=True, max_length=71, null=True)),
                ('drift_ok', models.BooleanField(default=True)),
                ('inputs', models.JSONField(default=dict)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('cost_micro', models.BigIntegerField(default=0)),
                ('caller_agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs_initiated', to='agents.agent')),
                ('goal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='goals.goal')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='plans.plan')),
                ('world', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='worlds.world')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='RunArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('in', 'Input'), ('out', 'Output')], max_length=3)),
                ('key', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artifact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='run_links', to='artifacts.artifact')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='runs.run')),
            ],
            options={
                'db_table': 'run_artifact',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='RunOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=128)),
                ('uri', models.CharField(max_length=512)),
                ('path', models.CharField(max_length=256)),
                ('content_type', models.CharField(blank=True, max_length=128)),
                ('size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('etag', models.CharField(blank=True, max_length=128)),
                ('sha256', models.CharField(blank=True, max_length=64)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outputs', to='runs.run')),
            ],
        ),
        migrations.AddIndex(
            model_name='run',
            index=models.Index(fields=['world', '-started_at'], name='run_world_started_idx'),
        ),
        migrations.AddIndex(
            model_name='run',
            index=models.Index(fields=['goal', '-started_at'], name='run_goal_started_idx'),
        ),
        migrations.AddIndex(
            model_name='run',
            index=models.Index(fields=['plan', '-started_at'], name='run_plan_started_idx'),
        ),
        migrations.AddIndex(
            model_name='run',
            index=models.Index(fields=['ref', '-started_at'], name='run_ref_started_idx'),
        ),
        migrations.AddIndex(
            model_name='runartifact',
            index=models.Index(fields=['run', 'direction'], name='run_artifac_run_id_01a190_idx'),
        ),
        migrations.AddIndex(
            model_name='runartifact',
            index=models.Index(fields=['artifact'], name='run_artifac_artifac_3d891e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='runartifact',
            unique_together={('run', 'direction', 'key')},
        ),
        migrations.AddIndex(
            model_name='runoutput',
            index=models.Index(fields=['run', 'key'], name='runs_runout_run_id_17c10c_idx'),
        ),
        migrations.AddIndex(
            model_name='runoutput',
            index=models.Index(fields=['uri'], name='runs_runout_uri_886a06_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='runoutput',
            unique_together={('run', 'key')},
        ),
    ]
