# Generated by Django 5.1.12 on 2025-10-05 03:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0002_initial'),
        ('goals', '0001_initial'),
        ('plans', '0001_initial'),
        ('worlds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ref', models.CharField(max_length=128)),
                ('ref_slug', models.CharField(max_length=128)),
                ('mode', models.CharField(max_length=8)),
                ('adapter', models.CharField(max_length=8)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('preempted', 'Preempted')], default='pending', max_length=16)),
                ('error_code', models.CharField(blank=True, max_length=64, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('write_prefix', models.CharField(max_length=512)),
                ('index_path', models.CharField(blank=True, max_length=512)),
                ('image_digest_expected', models.CharField(blank=True, max_length=71, null=True)),
                ('image_digest_actual', models.CharField(blank=True, max_length=71, null=True)),
                ('drift_ok', models.BooleanField(default=True)),
                ('meta', models.JSONField(default=dict)),
                ('inputs', models.JSONField(default=dict)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('cost_micro', models.BigIntegerField(default=0)),
                ('usage', models.JSONField(blank=True, null=True)),
                ('caller_agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs_initiated', to='agents.agent')),
                ('goal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='goals.goal')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='plans.plan')),
                ('world', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='worlds.world')),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['world', '-started_at'], name='run_world_started_idx'), models.Index(fields=['goal', '-started_at'], name='run_goal_started_idx'), models.Index(fields=['plan', '-started_at'], name='run_plan_started_idx'), models.Index(fields=['ref_slug', '-started_at'], name='run_ref_started_idx')],
            },
        ),
    ]
