# Generated by Django 5.1.12 on 2025-10-05 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RunOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=128)),
                ('uri', models.CharField(max_length=512)),
                ('path', models.CharField(max_length=256)),
                ('content_type', models.CharField(blank=True, max_length=128)),
                ('size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('etag', models.CharField(blank=True, max_length=128)),
                ('sha256', models.CharField(blank=True, max_length=64)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outputs', to='runs.run')),
            ],
            options={
                'indexes': [models.Index(fields=['run', 'key'], name='runs_runout_run_id_17c10c_idx'), models.Index(fields=['uri'], name='runs_runout_uri_886a06_idx')],
                'unique_together': {('run', 'key')},
            },
        ),
    ]
