# Generated by Django 5.1.12 on 2025-10-06 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_initial'),
        ('goals', '0001_initial'),
        ('plans', '0001_initial'),
        ('runs', '0002_runoutput'),
        ('worlds', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='run',
            name='run_ref_started_idx',
        ),
        migrations.RemoveField(
            model_name='run',
            name='ref_slug',
        ),
        migrations.AddIndex(
            model_name='run',
            index=models.Index(fields=['ref', '-started_at'], name='run_ref_started_idx'),
        ),
    ]
