# Generated by Django 5.1.12 on 2025-10-06 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artifacts', '0001_initial'),
        ('runs', '0003_remove_run_run_ref_started_idx_remove_run_ref_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RunArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('in', 'Input'), ('out', 'Output')], max_length=3)),
                ('key', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artifact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='run_links', to='artifacts.artifact')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='runs.run')),
            ],
            options={
                'db_table': 'run_artifact',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['run', 'direction'], name='run_artifac_run_id_01a190_idx'), models.Index(fields=['artifact'], name='run_artifac_artifac_3d891e_idx')],
                'unique_together': {('run', 'direction', 'key')},
            },
        ),
    ]
