# Generated by Django 5.1.12 on 2025-10-07 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0004_runartifact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='run',
            name='index_path',
        ),
        migrations.RemoveField(
            model_name='run',
            name='write_prefix',
        ),
    ]
