# Generated by Django 5.2 on 2025-09-07 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.PositiveBigIntegerField()),
                ('prev_hash', models.CharField(blank=True, max_length=128, null=True)),
                ('this_hash', models.CharField(max_length=128)),
                ('payload', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plans.plan')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('plan', 'seq'), name='uq_event_plan_seq')],
            },
        ),
    ]
