# Generated by Django 5.1.12 on 2025-10-05 03:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='World',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.SlugField(help_text="Stable slug. e.g. 'acme-campaign-q4'", max_length=64, unique=True)),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('settings_json', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worlds_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'world',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='WorldAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('editor', 'Editor'), ('viewer', 'Viewer')], default='editor', max_length=16)),
                ('budget_micro_override', models.BigIntegerField(blank=True, null=True)),
                ('concurrency_override', models.PositiveIntegerField(blank=True, null=True)),
                ('prefs', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='world_memberships', to='agents.agent')),
                ('world', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='worlds.world')),
            ],
            options={
                'db_table': 'world_agent',
                'indexes': [models.Index(fields=['world', 'role'], name='world_agent_world_i_3ecbda_idx')],
                'unique_together': {('world', 'agent')},
            },
        ),
    ]
