id: "0007"
area: rt
slug: leases-facade
title: Add LeaseManager facade and overlap checker (flag-gated no-op)
owner: engineer
state: closed
branch: feat/rt-leases-facade-0007
created: "2025-09-07T14:45:00Z"

scope:
  - Add `LeaseManager.acquire/release` facade (flag-gated no-op)
  - Canonicalize selectors; implement overlap checker (prefix/exact)
  - Unit tests for overlap true/false cases

non_goals:
  - No real lease persistence or scheduler integration
  - No path lease enforcement in runtime

acceptance:
  - make test-unit
  - cd code && pytest -q -k leases

outputs:
  - code/apps/core/leases/manager.py
  - code/apps/core/leases/__init__.py
  - code/apps/core/tests/test_leases_facade.py

gh:
  sync_mode: "issue-dryrun"
  title_pattern: "^{id} \[{area}\] {slug}$"
  labels: ["chat","area:rt"]
  issue_body_source: "SUMMARY.md"

ci_gates:
  - meta-schema
  - pr-title

notes: |
  Minimal façade to enable future admission checks; feature-flag default off. Focus on canonical path handling and safe overlap detection.
