# .pre-commit-config.yaml
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.0   # pin to match installed ruff version
    hooks:
      - id: ruff
        args: [--fix]         # auto-fix what can be fixed
      - id: ruff-format       # code formatter (Black-compatible style)

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: local
    hooks:
      - id: vulture
        name: vulture (dead code detection)
        entry: bash -c 'vulture code vulture_whitelist.py --min-confidence 80 --exclude "*/migrations/*" > vulture_report.txt || true'
        language: system
        files: '\.py$'
        require_serial: true
        pass_filenames: false
        always_run: true

      - id: unit-tests
        name: unit tests (fast hermetic checks)
        entry: make test-unit
        language: system
        files: '\.py$'
        require_serial: true
        pass_filenames: false
        always_run: true
