# .pre-commit-config.yaml
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.0   # pin to match installed ruff version
    hooks:
      - id: ruff
        args: [--fix]         # auto-fix what can be fixed
      - id: ruff-format       # code formatter (Black-compatible style)

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
