id: "0003"
slug: litellm
title: LLM — Standardize on LiteLLM substrate
area: rt
owner: twin
state: closed
created: "2025-09-05T00:00:00Z"
closed: "2025-09-05T00:00:00Z"
notes: Replace bespoke OpenAI/Ollama providers with a single LiteLLMProvider, keep MockLLM, add --api-base flag, update docs/settings/tests. No env-driven behavior.
branch: feat/rt-litellm-0003

scope:
  - Consolidate all LLM providers under LiteLLM
  - Add streaming support
  - Remove legacy provider implementations

non_goals:
  - Changes to World/Plan/Ledger architecture

acceptance:
  - python manage.py test apps.core.tests -v
  - python manage.py hello_llm --provider litellm --model openai/gpt-4o-mini

outputs:
  - apps/core/providers/litellm_provider.py
  - theory_api/docs/source/use-cases/hello-llm.md
  - .env.sample
