# Generated by Django 5.1.12 on 2025-10-08 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('worlds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('namespace', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=64)),
                ('version', models.PositiveIntegerField()),
                ('ref', models.CharField(max_length=160, unique=True)),
                ('ref_slug', models.CharField(db_index=True, max_length=160)),
                ('kind', models.CharField(choices=[('processor', 'Processor'), ('predicate', 'Predicate')], default='processor', max_length=16)),
                ('enabled', models.BooleanField(default=True)),
                ('inputs_schema', models.JSONField(blank=True, default=dict)),
                ('outputs_decl', models.JSONField(blank=True, default=list)),
                ('required_secrets', models.JSONField(blank=True, default=list)),
                ('registry_path', models.CharField(blank=True, default='', max_length=512)),
                ('digest_amd64', models.CharField(blank=True, default='', max_length=128)),
                ('digest_arm64', models.CharField(blank=True, default='', max_length=128)),
                ('timeout_s', models.PositiveIntegerField(default=600)),
                ('cpu', models.CharField(blank=True, default='1', max_length=8)),
                ('memory_gb', models.PositiveIntegerField(default=2)),
                ('gpu', models.CharField(blank=True, default='', max_length=32)),
            ],
            options={
                'indexes': [models.Index(fields=['ref_slug'], name='tools_tool_ref_slu_8f374b_idx'), models.Index(fields=['kind', 'enabled'], name='tools_tool_kind_84e68c_idx')],
                'unique_together': {('namespace', 'name', 'version')},
            },
        ),
        migrations.CreateModel(
            name='ToolIO',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('direction', models.CharField(choices=[('IN', 'Input'), ('OUT', 'Output')], max_length=3)),
                ('key', models.CharField(max_length=128)),
                ('schema', models.JSONField(blank=True, default=dict)),
                ('description', models.CharField(blank=True, default='', max_length=512)),
                ('path', models.CharField(blank=True, default='', max_length=256)),
                ('mime', models.CharField(blank=True, default='', max_length=128)),
                ('is_scalar_result', models.BooleanField(default=False)),
                ('role', models.CharField(blank=True, default='', max_length=64)),
                ('required', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ios', to='tools.tool')),
            ],
            options={
                'ordering': ['tool_id', 'direction', 'order', 'id'],
                'unique_together': {('tool', 'direction', 'key')},
            },
        ),
        migrations.CreateModel(
            name='WorldTool',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('quota_micro', models.BigIntegerField(blank=True, null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='world_bindings', to='tools.tool')),
                ('world', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='world_tools', to='worlds.world')),
            ],
            options={
                'indexes': [models.Index(fields=['world', 'enabled'], name='tools_world_world_i_18cf8c_idx')],
                'unique_together': {('world', 'tool')},
            },
        ),
    ]
