# Generated by Django 5.1.12 on 2025-10-05 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolIO',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('direction', models.CharField(choices=[('IN', 'Input'), ('OUT', 'Output')], max_length=3)),
                ('key', models.CharField(max_length=128)),
                ('schema', models.JSONField(blank=True, default=dict)),
                ('description', models.CharField(blank=True, default='', max_length=512)),
                ('path', models.CharField(blank=True, default='', max_length=256)),
                ('mime', models.CharField(blank=True, default='', max_length=128)),
                ('role', models.CharField(blank=True, default='', max_length=64)),
                ('required', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ios', to='tools.tool')),
            ],
            options={
                'ordering': ['tool_id', 'direction', 'order', 'id'],
                'unique_together': {('tool', 'direction', 'key')},
            },
        ),
    ]
