# Generated by Django 5.1.12 on 2025-10-05 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_add_is_scalar_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='cpu',
            field=models.CharField(blank=True, default='1', max_length=8),
        ),
        migrations.AddField(
            model_name='tool',
            name='gpu',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='tool',
            name='memory_gb',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='tool',
            name='timeout_s',
            field=models.PositiveIntegerField(default=600),
        ),
    ]
