# Generated by Django 5.1.12 on 2025-10-05 03:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tools', '0001_initial'),
        ('worlds', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=128)),
                ('title', models.CharField(blank=True, max_length=256)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('satisfied', 'Satisfied'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=16)),
                ('priority', models.PositiveIntegerField(blank=True, null=True)),
                ('satisfied_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('labels', models.JSONField(blank=True, null=True)),
                ('meta', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_goals', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='goals.goal')),
                ('predicate_tool', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='goals_using_predicate', to='tools.tool')),
                ('world', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='worlds.world')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='GoalPredicate',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=128)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('unknown', 'Unknown'), ('true', 'True'), ('false', 'False'), ('error', 'Error')], default='unknown', max_length=16)),
                ('last_payload', models.JSONField(blank=True, default=dict)),
                ('last_error', models.TextField(blank=True, default='')),
                ('last_evaluated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predicates', to='goals.goal')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goal_predicates', to='tools.tool')),
                ('world', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predicates', to='worlds.world')),
            ],
        ),
        migrations.AddIndex(
            model_name='goal',
            index=models.Index(fields=['world', 'status'], name='goals_goal_world_i_6f2241_idx'),
        ),
        migrations.AddIndex(
            model_name='goal',
            index=models.Index(fields=['parent'], name='goals_goal_parent__9fe865_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='goal',
            unique_together={('world', 'key')},
        ),
        migrations.AddIndex(
            model_name='goalpredicate',
            index=models.Index(fields=['world', 'goal'], name='goals_goalp_world_i_0da63c_idx'),
        ),
        migrations.AddIndex(
            model_name='goalpredicate',
            index=models.Index(fields=['status'], name='goals_goalp_status_d0962b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='goalpredicate',
            unique_together={('goal', 'key')},
        ),
    ]
