id: "0022"
area: rt
slug: processor-multitalk-modal
title: Containerized Multitalk processor on Modal
branch: feat/rt-processor-multitalk-modal-0022
created: "2025-09-08T00:00:00Z"
scope:
  - Implement multitalk/modal@1 with per-processor Dockerfile, GPU profile
  - Add artifact outputs (video + meta), success predicates, and determinism receipts

non_goals:
  - Full live streaming plane or SFU
  - Leases enforcement beyond façade flag

acceptance:
  - "Registry entry includes image.oci, runtime (cpu/memory/gpu exact), adapter.modal.opts, secrets."
  - "CLI: multiple attachments (first_frame, audio, etc.) -> $artifact; multi-asset messages supported."
  - "Success predicates pass: artifact.exists@1 (output mp4), artifact.jmespath_ok@1 (meta.json duration_ms>0)."
  - "Reserve->settle correct: reserved -= R; spent += A; refund = R-A; determinism.json written with input_cids/output_cids."

outputs:
  - code/apps/core/processors/multitalk_modal/Dockerfile
  - code/apps/core/processors/multitalk_modal/processor.py
  - code/apps/core/registry/processors/multitalk_modal.yaml
  - docs/source/use-cases/media-generation.md

ci_gates:
  - "cd code && pytest -q -m 'ledger_acceptance or requires_postgres'"
  - "cd code && sphinx-build -W -b html docs docs/_build/html"

notes: "Tags: runtime, modal, gpu, media. GPU-accelerated video processing with Modal."

owner: architect
state: open
