# Generated by Django 5.2 on 2025-09-07 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=128, unique=True)),
                ('reserved_micro', models.BigIntegerField(default=0)),
                ('spent_micro', models.BigIntegerField(default=0)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('reserved_micro__gte', 0)), name='plan_reserved_nonneg'), models.CheckConstraint(condition=models.Q(('spent_micro__gte', 0)), name='plan_spent_nonneg')],
            },
        ),
    ]
