# Generated by Django 5.1.12 on 2025-10-05 03:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0002_initial'),
        ('goals', '0001_initial'),
        ('worlds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=128)),
                ('title', models.CharField(blank=True, default='', max_length=256)),
                ('description', models.TextField(blank=True, default='')),
                ('spec', models.JSONField(default=dict)),
                ('defaults', models.JSONField(default=dict)),
                ('budget_micro', models.BigIntegerField(default=0)),
                ('spent_micro', models.BigIntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('abandoned', 'Abandoned')], default='draft', max_length=16)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agents.agent')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='goals.goal')),
                ('world', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='worlds.world')),
            ],
            options={
                'indexes': [models.Index(fields=['world', 'goal'], name='plans_plan_world_i_ce9f8d_idx'), models.Index(fields=['status'], name='plans_plan_status_bc420d_idx')],
                'unique_together': {('world', 'key')},
            },
        ),
    ]
