# Generated by Django 5.2 on 2025-09-08 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_project_plan_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plans', to='plans.project'),
        ),
    ]
