name: base
channels:
  - conda-forge
dependencies:
  - pip
  - setuptools
  - wheel
  - pip:
      - asgiref==3.9.1
      - django==5.2.5
      - sqlparse==0.5.3
      - dj-database-url==2.1.0
      - djangorestframework==3.14.0
      - graphene-django==3.2.0
      - boto3==1.40.21
      - django-storages==1.14.6
      - minio==7.2.16
      - redis==5.2.0
      - django-redis==5.4.0
      - sphinx==7.2.6
      - myst-parser==2.0.0
      - sphinxcontrib-mermaid==0.9.2
      - sphinx-jsonschema==1.19.1
      - sphinx-autobuild==2024.2.4
      - furo==2024.1.29
