id: "0010"
area: dc
slug: docs-drift-check
title: Enforce docs drift check + Sphinx -W
owner: architect
state: closed
branch: feat/dc-docs-drift-check-0010
created: "2025-09-07T16:30:00Z"

scope:
  - "Add GitHub Action: export generated docs, fail on drift, build Sphinx with -W"
  - "Keep CI PR-gated; no secrets"

non_goals:
  - No code behavior changes
  - No live deploy hooks

acceptance:
  - make docs
  - (in PR) drift causes CI failure on docs/_generated/** difference

outputs:
  - .github/workflows/docs.yml

gh:
  sync_mode: "issue-dryrun"
  title_pattern: '^{id} \[{area}\] {slug}$'
  labels: ["chat","area:dc"]
  issue_body_source: "SUMMARY.md"

ci_gates:
  - meta-schema
  - pr-title

notes: |
  Small CI-only change to lock "docs as contracts". Use Makefile target `make docs` locally; CI runs equivalent steps.
