id: "0005"
area: dx
slug: gh-sync
title: GitHub sync + clarify Twin-owned chat meta
owner: twin
state: open
branch: feat/dx-gh-sync-0005
created: "2025-09-05T00:00:00Z"

scope:
  - Make the Digital Twin the author of each chat's meta.yaml (contract of the "world")
  - "Update prompts to reflect: chats/, Twin-as-preference-model, branch/PR conventions"
  - "CI: validate meta.yaml schema + PR title pattern"
  - "Optional GH Issue sync: dry-run now; live later when we flip a switch"
  - "Comms Protocol: formalize files-only messaging + tools + CI validation"

non_goals:
  - No product semantics change (ledger/storage/leases unaffected)
  - No secrets in prompts or workflows

acceptance:
  - python theory_api/agents/validate_chat_meta.py $(find theory_api/agents/chats -name meta.yaml)
  - python theory_api/agents/validate_chat_msgs.py $(find theory_api/agents/chats -maxdepth 1 -type d)
  - make -C theory_api/docs -W html

outputs:
  - theory_api/agents/prompts/digital-twin.md (updated)
  - theory_api/agents/prompts/AGENTS.md (updated)
  - theory_api/agents/prompts/architect.md (updated)
  - theory_api/agents/prompts/engineer.md (updated)
  - theory_api/agents/prompts/communication-protocol.md
  - theory_api/agents/tools/post_chat.py
  - theory_api/agents/validate_chat_msgs.py
  - .github/workflows/agents-meta.yml (added/updated)
  - theory_api/agents/validate_chat_meta.py (schema updated)

gh:
  sync_mode: "issue-dryrun"     # none|issue-dryrun|issue-live
  title_pattern: "^{id} \\[{area}\\] {slug}$"
  labels: ["chat","area:dx"]
  issue_body_source: "SUMMARY.md"

ci_gates:
  - meta-schema
  - pr-title

notes: Land guardrails first; flip sync_mode to issue-live later if desired.
