id: "0000"
slug: migrate-north-star
title: Migrate North Star + Storage Context into Docs
area: dc
owner: twin
state: closed
created: "2025-09-05T00:00:00Z"
closed: "2025-09-05T00:00:00Z"
notes: Minimal migration of main narrative context into Sphinx docs with clear non-normative disclaimers.
branch: feat/dc-migrate-north-star-0000

scope:
  - Migrate documentation to Theory API structure
  - Establish North Star architecture

non_goals:
  - Runtime implementation changes

acceptance:
  - make -C theory_api/docs -W html

outputs:
  - theory_api/docs/source/index.md
  - theory_api/docs/source/concepts/*.md
