# Generated by Django 5.1.12 on 2025-10-08 20:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('value_ref', models.CharField(help_text="Format: 'env:VAR_NAME' or 'kms:ARN' (extend as needed)", max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'agent_credential',
            },
        ),
        migrations.CreateModel(
            name='AgentTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('default_inputs_override', models.JSONField(blank=True, null=True)),
                ('budget_micro_override', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'agent_tool',
            },
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('kind', models.CharField(choices=[('human', 'Human'), ('autonomous', 'Autonomous')], default='human', max_length=24)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('budget_micro_cap', models.BigIntegerField(blank=True, help_text='Global budget cap; null = use settings.DEFAULT_AGENT_BUDGET_MICRO', null=True)),
                ('concurrency_limit', models.PositiveIntegerField(blank=True, help_text='Global concurrency; null = use settings.DEFAULT_AGENT_CONCURRENCY', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='agents.agent')),
            ],
            options={
                'db_table': 'agent',
            },
        ),
    ]
