# Generated by Django 5.1.12 on 2025-10-08 20:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
        ('tools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agentcredential',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='agents.agent'),
        ),
        migrations.AddField(
            model_name='agenttool',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_permissions', to='agents.agent'),
        ),
        migrations.AddField(
            model_name='agenttool',
            name='world_tool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_permissions', to='tools.worldtool'),
        ),
        migrations.AddIndex(
            model_name='agent',
            index=models.Index(fields=['kind'], name='agent_kind_99f5c8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='agentcredential',
            unique_together={('agent', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='agenttool',
            unique_together={('agent', 'world_tool')},
        ),
    ]
