# Generated by Django 5.1.12 on 2025-10-05 03:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenttool',
            name='world_tool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_permissions', to='tools.worldtool'),
        ),
        migrations.AddIndex(
            model_name='agent',
            index=models.Index(fields=['kind'], name='agent_kind_99f5c8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='agentcredential',
            unique_together={('agent', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='agenttool',
            unique_together={('agent', 'world_tool')},
        ),
    ]
