# Generated by Django 5.2 on 2025-09-07 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('runnable', 'runnable'), ('applying', 'applying'), ('running', 'running'), ('succeeded', 'succeeded'), ('failed', 'failed')], default='pending', max_length=16)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plans.plan')),
            ],
        ),
        migrations.CreateModel(
            name='Execution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_idx', models.PositiveIntegerField()),
                ('transition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='runtime.transition')),
            ],
        ),
        migrations.AddConstraint(
            model_name='transition',
            constraint=models.UniqueConstraint(fields=('plan', 'key'), name='uq_transition_plan_key'),
        ),
        migrations.AddConstraint(
            model_name='transition',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['applying', 'running'])), fields=('plan',), name='uq_plan_single_writer'),
        ),
        migrations.AddConstraint(
            model_name='execution',
            constraint=models.UniqueConstraint(fields=('transition', 'attempt_idx'), name='uq_execution_attempt'),
        ),
    ]
