name: Cleanup Modal

on:
  schedule:
    - cron: '0 2 * * *'  # 2 AM UTC daily
  workflow_dispatch: {}

concurrency:
  group: cleanup-modal
  cancel-in-progress: false

jobs:
  cleanup:
    name: Clean Stale Modal Deployments
    runs-on: ubuntu-latest
    env:
      DJANGO_SETTINGS_MODULE: backend.settings.dev_remote
      APP_ENV: dev
      MODAL_TOKEN_ID: ${{ secrets.MODAL_TOKEN_ID }}
      MODAL_TOKEN_SECRET: ${{ secrets.MODAL_TOKEN_SECRET }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Need all branches for comparison
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip
          cache-dependency-path: |
            requirements.txt
            requirements-dev.txt
      - run: pip install -r requirements.txt -r requirements-dev.txt

      - name: Clean stale Modal deployments
        run: |
          echo "→ Scanning Modal deployments for stale branches..."

          # Get all Modal app names
          # Expected format: {branch}-{user}-{ref-slug}
          modal app list --env dev --json | jq -r '.[].name' | while read -r app_name; do
            # Skip if doesn't match branch pattern
            if ! echo "$app_name" | grep -qE '^[^-]+-[^-]+-[^-]+'; then
              echo "  ⊘ Skip: $app_name (doesn't match pattern)"
              continue
            fi

            # Extract branch by removing last two segments (user and ref)
            branch=$(echo "$app_name" | rev | cut -d'-' -f3- | rev)

            echo "  • $app_name → branch: $branch"

            # Check if branch exists
            if git show-ref --verify --quiet "refs/heads/$branch" || \
               git show-ref --verify --quiet "refs/remotes/origin/$branch"; then
              echo "    ✓ Branch exists, keeping deployment"
            else
              echo "    ✗ Branch deleted, stopping deployment"

              # Extract ref from app name
              ref_slug=$(echo "$app_name" | rev | cut -d'-' -f1-3 | rev)
              ref=$(echo "$ref_slug" | sed 's/-/\//; s/-v/@/')

              echo "    → Stopping: $ref (app: $app_name)"
              python code/manage.py modalctl stop --ref "$ref" || echo "    ⚠ Failed to stop $ref"
            fi
          done

          echo "✓ Cleanup complete"
