name: Dev Lane

on:
  push:
    branches: [ dev ]
    paths:
      - "code/**"
      - "tests/**"
      - ".github/workflows/dev.yml"
      - "Makefile"
  workflow_dispatch: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  quick-checks:
    runs-on: ubuntu-latest
    env:
      DJANGO_SETTINGS_MODULE: backend.settings.unittest
      TEST_LANE: dev
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - run: pip install -r requirements.txt -r requirements-dev.txt
      - name: Unit
        run: make test-unit
      - name: Integration
        run: make test-integration
      # Intentionally no build/pin/deploy here (dev is code-only integration).

  sync-secrets-dev:
    name: Sync secrets to Modal (dev)
    runs-on: ubuntu-latest
    env:
      MODAL_ENVIRONMENT: dev
      DJANGO_SETTINGS_MODULE: backend.settings.unittest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - run: pip install -r requirements.txt -r requirements-dev.txt
      - name: Install Modal CLI
        run: pip install modal-client
      - name: Sync secrets to Modal (dev)
        env:
          # Expose GitHub secrets as process environment variables
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          REPLICATE_API_TOKEN: ${{ secrets.REPLICATE_API_TOKEN }}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        working-directory: code
        run: |
          python manage.py sync_modal_secrets --env dev
