name: docs

on:
  pull_request:
    branches: [ dev, staging, main ]
  push:
    branches: [ main ]

jobs:
  check-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r code/requirements.txt
          pip install -r docs/requirements.txt

      - name: Export generated docs
        run: |
          cd code
          python manage.py docs_export --out ../docs/_generated --erd --api --schemas

      - name: Enforce no drift under docs/_generated/**
        run: |
          git diff --exit-code -- docs/_generated || (echo "::error::Generated docs changed. Run 'make docs' locally to export and commit updates." && exit 1)

      - name: Build Sphinx (warnings as errors)
        run: make -C docs -W html

      - name: Upload built docs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: docs-html
          path: docs/_build/html

