name: Docs (publish)

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "docs-publish"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      
      - name: Install docs dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r docs/requirements.txt
      
      - name: Setup Django for docs generation
        run: |
          cd code
          python manage.py docs_export --out ../docs/_generated --erd --api --schemas
      
      - name: Build docs (fail on warnings)
        working-directory: docs
        env:
          SPHINXOPTS: "-W"
        run: |
          make clean html
      
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/_build/html

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4