name: integration
on: { workflow_dispatch: {}, schedule: [{ cron: '0 6 * * *' }] }
jobs:
  live:
    runs-on: ubuntu-latest  # or self-hosted with Ollama preinstalled
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - run: pip install -r theory_api/docs/requirements.txt
      - run: pip install -r theory_api/code/requirements.txt
      - name: Run integration tests
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          cd theory_api/code
          pytest -m integration -q