name: Main Lane

on:
  push:
    branches: [ main ]
    paths:
      - "code/**"
      - "code/apps/core/processors/**"  # NEW source of truth for pins
      - ".github/workflows/main.yml"
      - "Makefile"
  workflow_dispatch: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  MODAL_ENVIRONMENT: main

jobs:
  deploy-and-test:
    name: Deploy to Modal (prod) and test
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      DJANGO_SETTINGS_MODULE: backend.settings.dev_remote
      ADAPTER: modal
      ENV: main
      PLATFORM: amd64
      MODAL_ENVIRONMENT: main
      TEST_ADAPTER: modal
      MOCK_MISSING_SECRETS: false
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - run: pip install -r requirements.txt -r requirements-dev.txt

      - name: Start tools on Modal (prod)
        env:
          MODAL_TOKEN_ID: ${{ secrets.MODAL_TOKEN_ID }}
          MODAL_TOKEN_SECRET: ${{ secrets.MODAL_TOKEN_SECRET }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          REPLICATE_API_TOKEN: ${{ secrets.REPLICATE_API_TOKEN }}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        run: make start-tools

      - name: Integration tests
        run: make test-integration
