name: PR Lane

on:
  pull_request:
    branches: [ dev ]
    paths:
      - "code/**"
      - "code/apps/core/processors/**"     # NEW: explicit processors
      - "tests/**"
      - ".github/workflows/pr.yml"
      - "Makefile"
  workflow_dispatch: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unit:
    runs-on: ubuntu-latest
    env:
      DJANGO_SETTINGS_MODULE: backend.settings.unittest
      TEST_LANE: pr
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - run: pip install -r requirements.txt -r requirements-dev.txt
      - name: Unit tests
        run: make test-unit

  integration:
    runs-on: ubuntu-latest
    needs: unit
    env:
      DJANGO_SETTINGS_MODULE: backend.settings.unittest
      TEST_LANE: pr
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - run: pip install -r requirements.txt -r requirements-dev.txt
      - name: Build processor image
        run: make build-processor REF=llm/litellm@1
      - name: Integration tests
        run: make integration-local-build

  contracts:
    runs-on: ubuntu-latest
    needs: integration
    timeout-minutes: 20
    env:
      DJANGO_SETTINGS_MODULE: backend.settings.unittest
      TEST_LANE: pr
      # PR lane invariants:
      LOG_STREAM: stderr               # keep stdout clean for --json
      RUN_TRANSPORT: "http"            # NEW: drive HTTP processors locally
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - run: pip install -r requirements.txt -r requirements-dev.txt
      - name: Contract tests (PR lane, mock, hermetic)
        run: make test-contracts
