name: PR Lane

on:
  pull_request:
    branches: [ dev ]
    paths:
      - "code/**"
      - "code/apps/core/processors/**"     # NEW: explicit processors
      - "tests/**"
      - ".github/workflows/pr.yml"
      - "Makefile"
  workflow_dispatch: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unit:
    runs-on: ubuntu-latest
    env:
      DJANGO_SETTINGS_MODULE: backend.settings.unittest
      TEST_LANE: pr
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - run: pip install -r requirements.txt -r requirements-dev.txt
      - name: Unit tests
        run: make test-unit

  integration:
    runs-on: ubuntu-latest
    env:
      DJANGO_SETTINGS_MODULE: backend.settings.dev_local
      ADAPTER: local
      PLATFORM: amd64
      MOCK_MISSING_SECRETS: true
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - run: pip install -r requirements.txt -r requirements-dev.txt

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run migrations
        run: cd code && python manage.py migrate --run-syncdb

      - name: Build and publish images
        run: make build-and-publish-all PLATFORM=amd64

      - name: Integration tests (local adapter)
        run: make test-integration

      - name: Cleanup
        if: always()
        run: make tools-cleanup && make services-down

  contracts:
    runs-on: ubuntu-latest
    timeout-minutes: 25
    env:
      DJANGO_SETTINGS_MODULE: backend.settings.unittest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - run: pip install -r requirements.txt -r requirements-dev.txt

      - name: Contract tests
        run: make test-contracts
