# Generated by Django 5.1.12 on 2025-10-08 20:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uri', models.CharField(db_index=True, max_length=1024)),
                ('path', models.CharField(blank=True, max_length=512)),
                ('data', models.JSONField(blank=True, null=True)),
                ('is_scalar', models.BooleanField(default=False)),
                ('content_type', models.CharField(blank=True, max_length=128)),
                ('size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('sha256', models.CharField(blank=True, db_index=True, max_length=64)),
                ('etag', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'artifact',
                'ordering': ['-created_at'],
            },
        ),
    ]
