# Generated by Django 5.1.12 on 2025-10-06 04:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('worlds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uri', models.CharField(db_index=True, max_length=1024)),
                ('path', models.CharField(blank=True, max_length=512)),
                ('data', models.JSONField(blank=True, null=True)),
                ('is_scalar', models.BooleanField(default=False)),
                ('content_type', models.CharField(blank=True, max_length=128)),
                ('size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('sha256', models.CharField(blank=True, db_index=True, max_length=64)),
                ('etag', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('world', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='worlds.world')),
            ],
            options={
                'db_table': 'artifact',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['world', 'path'], name='artifact_world_i_b72b3e_idx'), models.Index(fields=['world', 'sha256'], name='artifact_world_i_94d1c0_idx'), models.Index(fields=['world', '-created_at'], name='artifact_world_i_b9131b_idx'), models.Index(fields=['world', 'is_scalar'], name='artifact_world_i_0cdb4c_idx')],
                'constraints': [models.UniqueConstraint(fields=('world', 'uri'), name='artifact_world_uri_unique')],
            },
        ),
    ]
