# Generated by Django 5.2 on 2025-09-07 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uri', models.CharField(max_length=512)),
                ('content_hash', models.CharField(max_length=128)),
                ('content_type', models.CharField(blank=True, max_length=128)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plans.plan')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('plan', 'uri'), name='uq_artifact_plan_uri')],
            },
        ),
        migrations.CreateModel(
            name='ArtifactSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_key', models.CharField(max_length=256)),
                ('total_chunks', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plans.plan')),
            ],
            options={
                'verbose_name_plural': 'Artifact Series',
                'constraints': [models.UniqueConstraint(fields=('plan', 'series_key'), name='uq_artifact_series_plan_key')],
            },
        ),
    ]
