# Generated by Django 5.1.12 on 2025-10-08 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artifacts', '0001_initial'),
        ('worlds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifact',
            name='world',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='worlds.world'),
        ),
        migrations.AddIndex(
            model_name='artifact',
            index=models.Index(fields=['world', 'path'], name='artifact_world_i_b72b3e_idx'),
        ),
        migrations.AddIndex(
            model_name='artifact',
            index=models.Index(fields=['world', 'sha256'], name='artifact_world_i_94d1c0_idx'),
        ),
        migrations.AddIndex(
            model_name='artifact',
            index=models.Index(fields=['world', '-created_at'], name='artifact_world_i_b9131b_idx'),
        ),
        migrations.AddIndex(
            model_name='artifact',
            index=models.Index(fields=['world', 'is_scalar'], name='artifact_world_i_0cdb4c_idx'),
        ),
        migrations.AddConstraint(
            model_name='artifact',
            constraint=models.UniqueConstraint(fields=('world', 'uri'), name='artifact_world_uri_unique'),
        ),
    ]
